replicaCount: 1
image: "docker.elastic.co/elasticsearch/elasticsearch:7.17.22"
namespace: "elasticsearch"
resources:
  requests:
    cpu: "1"
    memory: "4Gi"
  limits:
    cpu: "1"
    memory: "4Gi"
env:
  - name: node.name
    value: "elasticsearch"
  - name: xpack.security.enabled
    value: "false"
  - name: discovery.type
    value: "single-node"
service:
  name: elasticsearch-images
  host: elasticsearch
  port: 9200
deployment:
  name: elasticsearch-images

persistence:
  enabled: true
  storageClass: "auto-ebs-sc"
  accessMode: ReadWriteOnce
  size: 10Gi

single_node_es: false