apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "ala-images.labels" . | nindent 4 }}
  name: "{{ .Values.rds.name }}"
spec:
  type: ExternalName
  externalName: {{ .Values.rds.externalName }}
  ports:
    - port: 5432
      targetPort: 5432