apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  labels:
    {{- include "ala-images.labels" . | nindent 4 }}
type: Opaque
data:
  image-service-config.yml: |-
    {{- tpl (.Files.Get "config/image-service-config.yml") . | b64enc | nindent 4 }}